window.DINNER_COMPARE_DATA = {
  brands: [
    {
      name: "HelloFresh",
      category: "Meal kit",
      bestFor: "Recipe variety and family planning",
      price: "Mid-range",
      countries: ["US", "UK", "Canada", "Australia"],
      deal: "First-box discount",
      rating: "8.8",
      affiliate: "/go/hellofresh/",
    },
    {
      name: "Factor",
      category: "Prepared meals",
      bestFor: "Busy weeks and high-protein convenience",
      price: "Premium",
      countries: ["US", "Canada"],
      deal: "New customer offer",
      rating: "8.9",
      affiliate: "/go/factor/",
    },
    {
      name: "Gousto",
      category: "Meal kit",
      bestFor: "UK recipe choice",
      price: "Good value",
      countries: ["UK"],
      deal: "First-box discount",
      rating: "8.6",
      affiliate: "/go/gousto/",
    },
    {
      name: "CookUnity",
      category: "Prepared meals",
      bestFor: "Chef-made ready meals",
      price: "Premium",
      countries: ["US"],
      deal: "Introductory discount",
      rating: "8.7",
      affiliate: "/go/cookunity/",
    },
  ],
};
